---
- name: install apache tomcat server
  hosts: all
  become: true
  
  tasks:
  - name: install java
    ansible.builtin.apt:
    name: default-jdk
  
  - name: install tomcat server packages
    get_url:
     url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
     dest: /usr/local
     
  - name: extract tomcat packages
    unarchive:
     src: /usr/local/apache-tomcat-10.0.27.tar.gz
     dest: /usr/local
     remote_src: yes
     
  - name: start tomact services
    shell: nohup /usr/local/apache-tomcat-10.0.27/bin/startup.sh
