---
- name: Install Tomcat Service 
  hosts: all
  root_user: manager
  become: true
  tasks:
   - name: Install latest openjdk-8
     apt:     ## apt-get install openjdk-8-jdk -y
      name: openjdk-8-jdk
      state: present
      update_cache: yes

   - name: add group "tomcat"
     group:  ## groupadd tomcat
       name: tomcat

   - name: add user "tomcat"
     user:  ## useradd tomcat -G tomcat
      name: tomcat
      group: tomcat
      createhome: no

   - name: Download and Extract archive
     unarchive:  ## download tomcat package and tar -xzf tarfile ## by default source is always controller
        src: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz
        dest: /opt
        remote_src: yes

   - name: create symlink
     file:   ## ln -s /opt/tomcat /opt/apache-tomcat-8.5.40
       src: /opt/apache-tomcat-8.5.40
       path: /opt/tomcat
       state: link

   - name: Change ownership of Tomcat installation
     file: ## chmod 755 -R /opt/tomcat , chown tomcat:tomcat -R /opt/tomcat
       path: /opt/tomcat
       owner: tomcat
       group: tomcat
       mode: 0755
       state: directory
       recurse: yes

   - name: create tomcat.service file
     file: ## touch /etc/systemd/system/tomcat.service
      path: /etc/systemd/system/tomcat.service
      state: touch

   - name: create tomcat service
     blockinfile:
       path: /etc/systemd/system/tomcat.service
       block: |
         [Unit]Description=Apache Tomcat Web Application Container
         After=network.targetd[Service]
         Type=forking
         Environment=JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre
         Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pidEnvironment=CATALINA_HOME=/opt/tomcat
         Environment=CATALINA_BASE=/opt/tomcat
         Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
         Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'
         
         ExecStart=/opt/tomcat/bin/startup.sh
         ExecStop=/opt/tomcat/bin/shutdown.sh
         User=tomcatGroup=tomcatUMask=0007
         RestartSec=10
         Restart=always[Install]
         WantedBy=multi-user.target
         
   - name: enable & start tomcat service
     systemd: ## systemctl enable tomcat, systecctl start tomcat
        name: tomcat
        state: started
        enabled: yes
        
   - name: validate tomcat is running
     shell: service tomcat status
     register: tstatus

   - debug:
       var: tstatus.stdout_lines
